version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Add common env vars
          command: |
            export IMAGE_TAG_PREFIX=$(echo branch-$CIRCLE_BRANCH | sed 's/\//-/' )
            echo "export IMAGE_NAME=applicaster/zapp-k8" >> $BASH_ENV
            echo "export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}" >> $BASH_ENV

      - run:
          name: Build application Docker image
          command: |
            export IMAGE_TAG_PREFIX=$(echo branch-master | sed 's/\//-/' )
            export IMAGE_NAME=applicaster
            export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}
            echo $(ls)
            docker build --tag ${CIRCLE_PROJECT_REPONAME}-0.1 .
      - run:
          name: checking
          command: |
           echo $(ls /caches/)

