version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Add common env vars
          command: |
            export IMAGE_TAG_PREFIX=$(echo branch-$CIRCLE_BRANCH | sed 's/\//-/' )
            echo "export IMAGE_NAME=applicaster/zapp-k8" >> $BASH_ENV
            echo "export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}" >> $BASH_ENV

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz; docker images;

      - run:
          name: Build application Docker image
          command: |
            echo $(ls)
            docker build --tag ${CIRCLE_PROJECT_REPONAME} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
#            docker build --tag ${CIRCLE_PROJECT_REPONAME} . | grep '\-\-\->' | grep -v 'Using cache' | sed -e 's/[ >-]//g' > /tmp/layers.txt
#            docker save $(cat /tmp/layers.txt) | gzip > /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz
            docker save -o /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz ${CIRCLE_PROJECT_REPONAME}
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - /caches/
      - run:
          name: checking
          command: |
           echo $(ls /caches/)