version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Add common env vars
          command: |
            export IMAGE_TAG_PREFIX=$(echo branch-$CIRCLE_BRANCH | sed 's/\//-/' )
            echo "export IMAGE_NAME=applicaster/zapp-k8" >> $BASH_ENV
            echo "export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}" >> $BASH_ENV

#      - restore_cache:
#          keys:
#            - v1-{{ .Branch }}
#          paths:
#            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/refactor.tar | true
      - run:
          name: Build application Docker image
          command: |
            export IMAGE_TAG_PREFIX=$(echo branch-master | sed 's/\//-/' )
            export IMAGE_NAME=applicaster
            export IMAGE_TAG=$IMAGE_TAG_PREFIX-${CIRCLE_SHA1:0:7}

            docker build --cache-from=refactor -t "$IMAGE_NAME:$IMAGE_TAG" -t "refactor" .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/refactor.tar refactor
#      - save_cache:
#          key: v1-{{ .Branch }}-{{ epoch }}
#          paths:
#            - /caches/app.tar
      - run:
          name: checking
          command: |
           echo $(ls /caches/)